# This is a basic workflow to help you get started with Actions

name: Testing-Path-Task
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
  uses: actions/setup-java@v3.5.0
  with:
    - name: Setup Java JDK
      uses: actions/setup-java@v3.5.0
        with:
