# name: Testing-Path-Task
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout source code
#       uses: actions/checkout@v3

#     - name: Steup Java
#       uses: actions/setup-java@v3
#       with:
#         distribution: 'temurin' 
#         java-version: '17'
    
#     - name: Run Java Test
#       run: java HelloWorldApp.java


name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
