name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.x'
      
      - name: Display Go version
        run: go version

      - name: Run build
        run: go mod init && go build . 